### ISSUE TITLE
🐛 BUG: SASS import of Bootstrap v4 results in 404

### ISSUE THREAD

**Issue by Porges** [snowpackjs/astro#686]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I have a component `src/components/Skeleton.tsx` that imports `../presentation/index.scss`. The SASS file is compiled (I can cause syntax errors by editing it) but the output .css is never found.

`npm start` shows:
```
[14:13:07] [snowpack] File changed: src/components/Skeleton.tsx
[access] /articles
[access] /_astro/src/presentation/index.css
[access] /_snowpack/hmr-client.js
[14:13:15] [snowpack] Build Result Error: There was a problem with a file build result.
[static] Not found /_astro/src/presentation/index.css
[access] /404
```

`npm build` shows:
```
[build] ! building pages...
[build] ✔ pages built.
[snowpack] Build Result Error: There was a problem with a file build result.
[build] Error: file:///workspaces/xxxxx/src/pages/articles.astro: could not find "index.css"
```

### Steps to Reproduce

See above

**Comment by Porges** [comment]
I tried to build a minimal repro, turns out the cause is an `@import` of Bootstrap. When I add it, it results in no compilation errors, but the result 404s.

Both of these “work” (don’t cause compilation errors) but result in 404:
```scss
@import 'bootstrap/scss/bootstrap.scss';
@import '../../node_modules/bootstrap/scss/bootstrap.scss';
```

**Comment by Porges** [comment]
Bootstrap 5 does seem to work correctly…

**Comment by jasikpark** [comment]
Hmmm apparently they switched from libsass to dart sass in the update - I wonder if there were any fixes they needed to do to make the switch?? https://getbootstrap.com/docs/5.0/migration/#dependencies

**Comment by Porges** [comment]
Not really a high-priority issue for me any more as I switched to v5 but it probably still needs investigation.

**Comment by borisv** [comment]
Neither @import nor @use seem to work since the 0.20 update. Whenever I put some scss with those statements inside any astro project the compiler looses track of the root param, throwing 404s. Right now I can not get any project making use of those statements to compile. Using at least 0.20.5 to 0.20.7.

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
